Feature/esacpe 1597
Terradue/Stars pull request #22
Opened 2023-08-04 14:23 UTC by bbrauzzi

STARS support for Pleiades NEO products

2023-08-23 09:30 UTC, emmanuelmathot requested changes

2023-08-23 09:30 UTC, emmanuelmathot commented on src/Stars.Data.Tests/Harvesters/MetadataExtractorsTests.cs
> +                WriteJson(Path.Join(datadir, "../.."), actualJson, stacItem.Id);
This must be commented back.

2023-08-23 12:15 UTC, bbrauzzi commented on src/Stars.Data.Tests/Harvesters/MetadataExtractorsTests.cs
> +                WriteJson(Path.Join(datadir, "../.."), actualJson, stacItem.Id);
yes, correct , sorry.
I made a review with Mauro and found out that there also other changes to be done.
I will keep you updated on the progress.
thanks

2023-08-28 08:15 UTC, emmanuelmathot approved these changes
ok

2023-08-28 08:16 UTC, merged